Feat/expand snapshot e2e test
Informatievlaanderen/VSDS-LDES-E2E-testing pull request #259
Opened 2023-04-18 08:08 UTC by pj-cegeka

2023-04-18 11:25 UTC, rorlic commented on demos/025.server-snapshot-ldes/docker-compose.yml
> +    image: sha256:29a947e5416d205f83c9173e2a3fffc0d0a7e79603181c55ed7efe6f802d7209 #ghcr.io/informatievlaanderen/ldes-server:${LDES_SERVER_TAG:-latest}
please revert this part

2023-04-20 07:11 UTC, sverholen approved these changes

2023-04-21 10:11 UTC, rorlic commented on demos/025.server-snapshot-ldes/README.md
> +    curl -X POST http://localhost:8080/admin/api/v1/mobility-hindrances/snapshots
does not work:
```
Unable to create snapshot.
Cause: No TreeNodes available in view by-page which is used for snapshotting
```

2023-04-21 10:11 UTC, rorlic requested changes
Please fix the test

2023-04-21 14:46 UTC, rorlic approved these changes

2023-04-21 14:55 UTC, merged